- hosts: appservers
- hosts: loadbalancers
  become: true
  roles:
  - role: ansible-pacemaker
  - role: haproxy_test
# - role: styopa.pacemaker

  vars:
    haproxy_package_name: haproxy
    #haproxy_frontend_port: 80
    haproxy_backend_port: 80
    node_exporter_package_name: node_exporter
    
    pacemaker_ansible_group: loadbalancers
    pacemaker_cluster_name: foobar
    pacemaker_password: vagrant

    # pacemaker_ring0_addr: ansible_all_ipv4_addresses
    # pacemaker_ring0_addr_interface: 1
    # pacemaker_properties:
    #   stonith_enabled: "false"
    # pacemaker_resources:
    #   - id:      virtual-ip
    #     type:    "ocf:heartbeat:IPaddr2"
    #     options:
    #       ip:           192.168.33.20  # this is the Virtual IP
    #       cidr_netmask: 24
    #       nic:          enp0s8
    #     op:
    #       - action:  monitor
    #         options:
    #           interval: 5s








